"use client";

import { useEffect, useState, useCallback, useMemo, useRef, startTransition } from "react";
import { useParams } from "next/navigation";
import { FileText, Swords } from "lucide-react";
import {
  getInvestigation,
  streamInvestigation,
  streamDebate,
  streamDraftMemo,
  getBriefing,
  type InvestigationSummary,
  type TraceEvent,
  type FollowUp,
  type DebateResult,
  type MemoEntry,
} from "@/lib/api";
import { useAuth } from "@/components/providers/AuthProvider";
import { AgentPanel } from "@/components/agent/AgentPanel";
import { useShellMainHeader } from "@/components/home/ShellMainHeader";
import { WorkspaceResizableLayout } from "@/components/workspace/WorkspaceResizableLayout";
import { SourcesPanel } from "@/components/workspace/SourcesPanel";
import { InvestigationDashboard, type InlineDebate } from "@/components/workspace/InvestigationDashboard";
import { BriefingModal } from "@/components/BriefingModal";
import { DebateModal } from "@/components/DebateModal";
import { DocumentModal } from "@/components/DocumentModal";
import { Button } from "@/components/ui/button";
import { InvestigationLoadingView } from "@/components/workspace/InvestigationLoadingView";

type TraceStep = {
  id?: number;
  step: string;
  status: string;
  message: string;
  timestamp?: string;
};

export default function WorkspacePage() {
  const params = useParams();
  const id = Number(params.id);
  const { user, refreshUser } = useAuth();

  const [query, setQuery] = useState("");
  const [summary, setSummary] = useState<InvestigationSummary | null>(null);
  const [traceSteps, setTraceSteps] = useState<TraceStep[]>([]);
  const [isRunning, setIsRunning] = useState(true);
  const [highlightMechanism, setHighlightMechanism] = useState<string | null>(null);
  const [showBriefing, setShowBriefing] = useState(false);
  const [briefingContent, setBriefingContent] = useState("");
  const [followups, setFollowups] = useState<FollowUp[]>([]);
  const [savedDebate, setSavedDebate] = useState<DebateResult | undefined>(undefined);
  const [showDebate, setShowDebate] = useState(false);
  const [debateBull, setDebateBull] = useState("");
  const [debateBear, setDebateBear] = useState("");
  const [debateSynthesis, setDebateSynthesis] = useState("");
  const [isDebating, setIsDebating] = useState(false);
  const [savedMemos, setSavedMemos] = useState<Record<string, MemoEntry>>({});
  const [showMemo, setShowMemo] = useState(false);
  const [memoTherapyName, setMemoTherapyName] = useState("");
  const [memoContent, setMemoContent] = useState("");
  const [isMemoStreaming, setIsMemoStreaming] = useState(false);
  const [inlineDebate, setInlineDebate] = useState<InlineDebate | null>(null);
  const [debateLoading, setDebateLoading] = useState(false);
  const [inlineLeadMemo, setInlineLeadMemo] = useState<{ therapyName: string; content: string } | null>(
    null,
  );
  const [leadMemoLoading, setLeadMemoLoading] = useState(false);

  const traceMapRef = useRef<Map<string, TraceStep>>(new Map());
  const traceFlushRef = useRef<number | null>(null);
  const autoGeneratedRef = useRef(false);

  const flushTraceSteps = useCallback(() => {
    traceFlushRef.current = null;
    setTraceSteps(Array.from(traceMapRef.current.values()));
  }, []);

  const queueTraceUpdate = useCallback(
    (event: TraceEvent) => {
      if (event.type !== "trace" || !event.step || !event.message) return;

      traceMapRef.current.set(event.step, {
        step: event.step,
        status: event.status || "running",
        message: event.message,
        timestamp: event.timestamp,
      });

      if (traceFlushRef.current === null) {
        traceFlushRef.current = window.requestAnimationFrame(flushTraceSteps);
      }
    },
    [flushTraceSteps]
  );

  const handleEvent = useCallback(
    (event: TraceEvent) => {
      if (event.type === "trace") {
        queueTraceUpdate(event);
        return;
      }

      if (event.type === "complete" && event.data) {
        setIsRunning(false);
        startTransition(() => {
          setSummary(event.data ?? null);
        });
      }
    },
    [queueTraceUpdate]
  );

  useEffect(() => {
    if (!id) return;

    autoGeneratedRef.current = false;
    let cleanup: (() => void) | undefined;
    traceMapRef.current = new Map();

    getInvestigation(id).then((inv) => {
      setQuery(inv.query);
      setFollowups(inv.followups || []);
      setSavedDebate(inv.debate);
      setSavedMemos(inv.memos || {});
      if (inv.debate) {
        setInlineDebate({
          bull: inv.debate.bull,
          bear: inv.debate.bear,
          synthesis: inv.debate.synthesis,
        });
      }
      const topTherapy = inv.summary?.rankings?.[0]?.name;
      if (topTherapy && inv.memos?.[topTherapy]) {
        setInlineLeadMemo({
          therapyName: topTherapy,
          content: inv.memos[topTherapy].content,
        });
      }

      if (inv.traces?.length) {
        setTraceSteps(inv.traces);
      }

      const savedTrials = inv.summary?.landscape?.total_trials ?? 0;
      const hasUsableSummary = Boolean(inv.summary) && savedTrials > 0;

      if (hasUsableSummary) {
        setSummary(inv.summary!);
        setIsRunning(false);
        return;
      }

      if (inv.summary && savedTrials === 0) {
        setSummary(null);
      }

      cleanup = streamInvestigation(
        id,
        handleEvent,
        () => {
          setIsRunning(false);
          refreshUser();
        },
        () => setIsRunning(false)
      );
    });

    return () => {
      if (traceFlushRef.current !== null) {
        window.cancelAnimationFrame(traceFlushRef.current);
      }
      cleanup?.();
    };
  }, [id, handleEvent, refreshUser]);

  useEffect(() => {
    if (isRunning || !summary || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;

    if (!savedDebate) {
      setDebateLoading(true);
      void streamDebate(
        id,
        (event) => {
          if (event.type !== "delta") return;
          setInlineDebate((prev) => ({
            bull: prev?.bull || "",
            bear: prev?.bear || "",
            synthesis: prev?.synthesis || "",
            [event.side]: (prev?.[event.side] || "") + event.content,
          }));
        },
        () => {
          setDebateLoading(false);
          getInvestigation(id).then((inv) => {
            if (inv.debate) {
              setSavedDebate(inv.debate);
              setInlineDebate({
                bull: inv.debate.bull,
                bear: inv.debate.bear,
                synthesis: inv.debate.synthesis,
              });
            }
          });
        },
        () => setDebateLoading(false),
      );
    }

    const topTherapy = summary.rankings[0]?.name;
    if (topTherapy && !savedMemos[topTherapy]) {
      setLeadMemoLoading(true);
      void streamDraftMemo(
        id,
        topTherapy,
        (event) => {
          if (event.type === "delta") {
            setInlineLeadMemo((prev) => ({
              therapyName: topTherapy,
              content: (prev?.content || "") + event.content,
            }));
          }
        },
        () => {
          setLeadMemoLoading(false);
          getInvestigation(id).then((inv) => {
            setSavedMemos(inv.memos || {});
            const memo = inv.memos?.[topTherapy];
            if (memo) {
              setInlineLeadMemo({ therapyName: topTherapy, content: memo.content });
            }
          });
        },
        () => setLeadMemoLoading(false),
      );
    }
  }, [id, isRunning, summary, savedDebate, savedMemos]);

  const handleBriefing = useCallback(async () => {
    const content = await getBriefing(id);
    setBriefingContent(content);
    setShowBriefing(true);
  }, [id]);

  const handleDebate = useCallback(async () => {
    const debate = savedDebate || (inlineDebate ? {
      bull: inlineDebate.bull,
      bear: inlineDebate.bear,
      synthesis: inlineDebate.synthesis,
      created_at: "",
    } : undefined);

    if (debate) {
      setDebateBull(debate.bull);
      setDebateBear(debate.bear);
      setDebateSynthesis(debate.synthesis);
      setShowDebate(true);
      return;
    }

    setDebateBull("");
    setDebateBear("");
    setDebateSynthesis("");
    setShowDebate(true);
    setIsDebating(true);

    await streamDebate(
      id,
      (event) => {
        if (event.type !== "delta") return;
        if (event.side === "bull") setDebateBull((prev) => prev + event.content);
        if (event.side === "bear") setDebateBear((prev) => prev + event.content);
        if (event.side === "synthesis") setDebateSynthesis((prev) => prev + event.content);
      },
      () => {
        setIsDebating(false);
        getInvestigation(id).then((inv) => setSavedDebate(inv.debate));
      },
      () => setIsDebating(false)
    );
  }, [id, savedDebate, inlineDebate]);

  const handleDraftMemo = useCallback(
    async (therapyName: string) => {
      const cached = savedMemos[therapyName];
      if (cached) {
        setMemoTherapyName(therapyName);
        setMemoContent(cached.content);
        setShowMemo(true);
        return;
      }

      setMemoTherapyName(therapyName);
      setMemoContent("");
      setShowMemo(true);
      setIsMemoStreaming(true);

      await streamDraftMemo(
        id,
        therapyName,
        (event) => {
          if (event.type === "delta") setMemoContent((prev) => prev + event.content);
        },
        () => {
          setIsMemoStreaming(false);
          getInvestigation(id).then((inv) => setSavedMemos(inv.memos || {}));
        },
        () => setIsMemoStreaming(false)
      );
    },
    [id, savedMemos]
  );

  const sourcesPanel = useMemo(
    () => <SourcesPanel investigationId={id} disabled={isRunning && !summary} />,
    [id, isRunning, summary]
  );

  const mainPanel = useMemo(
    () => (
      <div className="p-6">
        {isRunning && !summary && <InvestigationLoadingView investigationId={id} />}

        {summary && (
          <InvestigationDashboard
            summary={summary}
            query={query}
            highlightMechanism={highlightMechanism}
            debate={inlineDebate}
            debateLoading={debateLoading}
            leadMemo={inlineLeadMemo}
            leadMemoLoading={leadMemoLoading}
            onHighlight={setHighlightMechanism}
            onDraftMemo={handleDraftMemo}
            onOpenDebate={handleDebate}
          />
        )}

        {!summary && !isRunning && (
          <p className="py-12 text-center text-sm text-muted-foreground">No data available.</p>
        )}
      </div>
    ),
    [isRunning, summary, query, highlightMechanism, handleDraftMemo, inlineDebate, debateLoading, inlineLeadMemo, leadMemoLoading, handleDebate]
  );

  const agentPanel = useMemo(
    () => (
      <>
        <div className="flex shrink-0 items-center justify-between rounded-t-xl px-4 pb-3 pt-3">
          <p className="text-xs uppercase tracking-widest text-muted-foreground">Agent</p>
          {!isRunning && (
            <div className="flex items-center gap-2">
              <Button variant="outline" size="xs" onClick={handleBriefing}>
                <FileText className="h-3.5 w-3.5" />
                Briefing
              </Button>
              <Button variant="outline" size="xs" onClick={handleDebate}>
                <Swords className="h-3.5 w-3.5" />
                Debate
              </Button>
            </div>
          )}
        </div>
        <div className="min-h-0 flex-1 overflow-hidden px-4 pb-4">
          <AgentPanel
            investigationId={id}
            signals={summary?.signals || []}
            traceSteps={traceSteps}
            isRunning={isRunning}
            savedFollowups={followups}
            onHighlight={setHighlightMechanism}
          />
        </div>
      </>
    ),
    [id, summary, traceSteps, isRunning, followups, handleBriefing, handleDebate]
  );

  useShellMainHeader(query || null);

  if (!user) return null;

  return (
    <>
      <div className="flex h-full min-h-0 flex-col">
        <WorkspaceResizableLayout
          sources={sourcesPanel}
          main={mainPanel}
          agent={agentPanel}
        />
      </div>

      <BriefingModal
        open={showBriefing}
        content={briefingContent}
        onClose={() => setShowBriefing(false)}
      />

      <DebateModal
        open={showDebate}
        bull={debateBull}
        bear={debateBear}
        synthesis={debateSynthesis}
        isStreaming={isDebating}
        onClose={() => setShowDebate(false)}
      />

      <DocumentModal
        open={showMemo}
        title={`BD memo — ${memoTherapyName}`}
        content={memoContent || (isMemoStreaming ? "" : "No memo generated.")}
        loading={isMemoStreaming}
        onClose={() => setShowMemo(false)}
      />
    </>
  );
}
